language: node_js
node_js:
    - '14'
cache:
    directories:
        - 'node_modules'
install:
    - npm install
script:
    - npm run build-chrome
    - npm run build-firefox
deploy:
    - provider: script
      cleanup: true
      script: bash scripts/upload-chrome.sh
      on:
          branch: master
    - provider: script
      cleanup: true
      script: bash scripts/upload-firefox.sh
      on:
          branch: master
